version: "3"
services:
  app:
    image: gasoilrata
    container_name: gasoilrata-container
    build: ./
    restart: always
    ports:
      - "81:80"
    volumes:
      - .:/var/www/html
  myadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - "82:80"
    links:
      - mysql:db
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSOL_HOST: 0.0.0.0
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

volumes:
    mysql:
      driver: "local"
